#!/bin/bash

set -e

MSG="Usage: disk create <outpu-path> <size>\nCreate new .qcow2 virtual disk"

if [ "$1" = "help" ] || [ "$1" = "h" ]; then
  echo -e "$MSG"
  exit 0
fi

if [[ $# -ne 2 ]]; then
  echo -e "$MSG"
  exit 1
fi

DISK_PATH="$1"
DISK_SIZE="$2"

if [[ -e "$DISK_PATH" ]]; then
  echo "Error: File '$DISK_PATH' already exists"
  exit 2
fi

qemu-img create -f qcow2 "$DISK_PATH.qcow2" "$DISK_SIZE"

if [[ $? -eq 0 ]]; then
  echo "Disk image created: $DISK_PATH ($DISK_SIZE)"
  exit 0
fi

echo "Failed to create disk image"
exit 3
