#!/bin/bash

set -e

MSG="Usage: disk destroy <disk-path>\nDelete virtual disk"

if [ "$1" = "help" ] || [ "$1" = "h" ]; then
  echo -e "$MSG"
  exit 0
fi

if [[ $# -ne 1 ]]; then
  echo -e "$MSG"
  exit 1
fi

DISK_PATH="$1"

if [[ ! -f "$DISK_PATH" ]]; then
  echo "Error: File '$DISK_PATH' does not exist or is not a regular file"
  exit 2
fi

read -p "Are you sure you want to delete '$DISK_PATH'? [y/N]: " CONFIRM
if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
  echo "Aborted"
  exit 3
fi

rm -f "$DISK_PATH"

if [[ $? -eq 0 ]]; then
  echo "Disk image '$DISK_PATH' deleted successfuly"
  exit 0
fi

echo "Failed to delete disk image"
exit 3
