#!/bin/bash

set -e

MSG="Usage: edit <vm-name>\nEdit an already defined VM"

if [ "$1" = "help" ] || [ "$1" = "h" ]; then
  echo -e "$MSG"
  exit 0
fi

if [[ $# -ne 1 ]]; then
  echo -e "$MSG"
  exit 1
fi

VM_NAME="$1"

echo "Opening XML definition for VM '$VM_NAME'..."
virsh edit "$VM_NAME"
