#!/bin/bash

set -e

MSG="Usage: status <vm-name>\nReturn the defined VM status"

if [ "$1" = "help" ] || [ "$1" = "h" ]; then
  echo -e "$MSG"
  exit 0
fi

if [[ $# -ne 1 ]]; then
  echo -e "$MSG"
  exit 1
fi

VM_NAME="$1"

echo "Status form VM '$VM_NAME'"
virsh dominfo "$VM_NAME"
